// Generated by `npm run data` from the gitignored workbook in data/. Do not edit by hand.
import dataset from '../data/federal-funds.json';

export const { meta, headline, areas, agencies, stressTests } = dataset;

export function formatMoney(dollars) {
  const abs = Math.abs(dollars);
  if (abs >= 1e9) return `$${(dollars / 1e9).toFixed(2)}B`;
  if (abs >= 1e6) return `$${Math.round(dollars / 1e6).toLocaleString()}M`;
  return `$${Math.round(dollars).toLocaleString()}`;
}

export function formatPercent(ratio, digits = 1) {
  return `${(ratio * 100).toFixed(digits)}%`;
}
